[window]
startup_mode = "Fullscreen"
padding = { x = 5, y = 5 }


[font]
#normal = { family = "MesloLGS NF", style = "Regular" }
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 14

[colors.primary]
#background = '#2c2b2a'
#foreground = '#ebdbb2'
background = '#282828'
foreground = '#d4be98'

# Normal colors
[colors.normal]
black   = '#282828'
#red     = '#cc241d'
red     = '#fb4934'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
#white   = '#a89984'
white   = '#d4be98'

# Bright colors
[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'
